/* Document-reviewed disposal sites. Coordinates are address/facility points, not surveyed bins. */
(function(root){
  "use strict";
  const entries = {
  "bin_seocho-yangjae-park": {
    "name": "양재근린공원 분변수거함",
    "address": "서울 서초구 양재동 311",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-picheondeuk": {
    "name": "반포천·피천득 산책로 분변수거함",
    "address": "서울 서초구 반포동 117-14",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-sindong": {
    "name": "신동근린공원 분변수거함",
    "address": "서울 서초구 잠원동 58-14",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-bangbae-saigil": {
    "name": "방배사이길공원 분변수거함",
    "address": "서울 서초구 방배동 18-19",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-yangjae-stage": {
    "name": "양재천 수변무대 인근 분변수거함",
    "address": "서울 서초구 양재동 99-4",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-havel": {
    "name": "양재천 하벨벤치 인근 분변수거함",
    "address": "서울 서초구 양재동 261-23",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-sowon": {
    "name": "여의천 소원카페 뒤 데크 분변수거함",
    "address": "서울 서초구 양재동 238 1층",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-maljuk": {
    "name": "말죽거리공원 분변수거함",
    "address": "서울 서초구 양재동 산 20-2",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-sinbanpo": {
    "name": "신반포공원 산책로 분변수거함",
    "address": "서울 서초구 반포동 117-3",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-banpo-underpass": {
    "name": "반포나들목 산책로 분변수거함",
    "address": "서울 서초구 잠원동 80",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-montmartre": {
    "name": "몽마르뜨공원 분변수거함",
    "address": "서울 서초구 반포동 산 59-1",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-gilmajung2": {
    "name": "길마중2교 분변수거함",
    "address": "서울 서초구 서초동 1418",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-gilmajung1": {
    "name": "길마중1교 분변수거함",
    "address": "서울 서초구 서초동 1377-1",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_seocho-bangbae-police": {
    "name": "방배복개도로 산책로·방배경찰서 앞 분변수거함",
    "address": "서울 서초구 방배동 493-2",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/seocho88/224282926602",
    "provider": "서초구 공식 블로그",
    "sourceDate": "2026-05-12",
    "checkedDate": "2026-10-08",
    "pointType": "공개 주소 기준 위치",
    "positionNote": "공개 주소 기준 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "서초구의 2026년 4월 위치 안내에 등재된 분변수거함입니다. 배설물을 담은 봉투만 넣고 일반 쓰레기는 버리지 마세요. 현장에 표시된 봉투 종류와 이용 방법을 확인하세요.",
    "secondary": ""
  },
  "bin_incheon-wolmi": {
    "name": "월미공원 반려견놀이터 스마트 배변수거함",
    "address": "인천 제물포구 북성동1가 102-2",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-namhang": {
    "name": "남항근린공원 스마트 배변수거함",
    "address": "인천 제물포구 신흥동3가 69",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-rose": {
    "name": "장미근린공원 스마트 배변수거함",
    "address": "인천 연수구 연수동 137-3",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-mujugol": {
    "name": "무주골공원 스마트 배변수거함",
    "address": "인천 연수구 선학동 441",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-gyeyang": {
    "name": "계양공원 스마트 배변수거함",
    "address": "인천 계양구 계산동 산 52-1",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-songhyeon": {
    "name": "송현근린공원 스마트 배변수거함",
    "address": "인천 제물포구 송현동 23-62",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-incheongyo": {
    "name": "인천교근린공원 스마트 배변수거함",
    "address": "인천 제물포구 송림동 326",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-hyeyum": {
    "name": "혜윰공원 스마트 배변수거함",
    "address": "인천 연수구 송도동 199-2",
    "kind": "스마트 배변 수거함",
    "source": "https://www.incheon.go.kr/mayor_8/MA040101/view?curPage=414&repSeq=DOM_0000000009329884",
    "provider": "인천광역시",
    "sourceDate": "2024-02-20",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-buyeong": {
    "name": "부영공원 스마트 배변수거함",
    "address": "인천 부평구 산곡동",
    "kind": "스마트 배변 수거함",
    "source": "https://www.icbp.go.kr/newsWebzine/newsWebzineNo/newsWebzineNoDetail.do?menudetail=11&no_seq=9170&pgno=3",
    "provider": "부평구청",
    "sourceDate": "2024-04-25",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-sintri": {
    "name": "신트리공원 스마트 배변수거함",
    "address": "인천 부평구 부평동 891",
    "kind": "스마트 배변 수거함",
    "source": "https://www.icbp.go.kr/newsWebzine/newsWebzineNo/newsWebzineNoDetail.do?menudetail=11&no_seq=9170&pgno=3",
    "provider": "부평구청",
    "sourceDate": "2024-04-25",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_incheon-majang": {
    "name": "마장공원 스마트 배변수거함",
    "address": "인천 부평구 산곡동 261-1",
    "kind": "스마트 배변 수거함",
    "source": "https://www.icbp.go.kr/newsWebzine/newsWebzineNo/newsWebzineNoDetail.do?menudetail=11&no_seq=9170&pgno=3",
    "provider": "부평구청",
    "sourceDate": "2024-04-25",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "설치 자료에서 배변봉투 지급과 수거 기능을 확인했습니다. 풉풉(PUPPOOP) 앱 가입과 수거용 QR 인증이 필요합니다. 전용 봉투·QR 이용 방법, 기기 작동과 수거함 포화 상태를 현장에서 확인하세요.",
    "secondary": "https://v.daum.net/v/x2O84zZvZi"
  },
  "bin_gyeonggi-peace": {
    "name": "경기평화광장·경기도 북부청사 배변수거함",
    "address": "경기도 의정부시 청사로 1",
    "kind": "배변 수거함",
    "source": "https://gnews.gg.go.kr/briefing/brief_gongbo_view.do?BS_CODE=s017&number=60961&subject_Code=BO01",
    "provider": "경기도",
    "sourceDate": "2024-03-26",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "경기평화광장과 별관 앞 보도 화단에 배변봉투 수거함 2곳이 설치된 자료를 확인했습니다. 같은 청사 내 시설을 하나의 장소로 묶었습니다.",
    "secondary": ""
  },
  "bin_gwanggyo": {
    "name": "광교호수공원 반려견놀이터 배변수거함",
    "address": "경기도 수원시 영통구 하동 1008-9",
    "kind": "배변 수거함",
    "source": "https://www.gg.go.kr/myggd/vol158/sub1_4.html",
    "provider": "경기도 공식 매거진",
    "sourceDate": null,
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "신대호수 주차장 뒤편 반려견놀이터의 배변봉투 수거함을 안내합니다. 동물등록과 놀이터 입장 조건·운영시간을 확인하고 지정 구역에서 이용하세요.",
    "secondary": ""
  },
  "bin_saneum": {
    "name": "국립산음자연휴양림 반려견운동장 배변수거함",
    "address": "경기도 양평군 단월면 고북길 347",
    "kind": "배변 수거함",
    "source": "https://www.gg.go.kr/myggd/vol158/sub1_4.html",
    "provider": "경기도 공식 매거진",
    "sourceDate": null,
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "반려견운동장 내 배변봉투 수거함 설치 안내를 확인했습니다. 예약·입장과 반려견 허용 조건이 있는 시설입니다. 휴양림 이용객 대상인지와 운동장 이용 범위를 관리소에 먼저 확인하세요.",
    "secondary": ""
  },
  "bin_majung": {
    "name": "마중공원 반려견놀이터 배변수거함",
    "address": "경기 수원시 권선구 권선동 1348",
    "kind": "배변 수거함",
    "source": "https://blog.naver.com/suwonloves/223913639914",
    "provider": "수원시 공식 블로그",
    "sourceDate": null,
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "수원시 SNS 서포터즈의 팻 파크 취재에서 배변봉투 수거함을 확인했습니다. 놀이터 운영시간과 동물등록 등 입장 조건을 확인하세요.",
    "secondary": ""
  },
  "bin_daeyupyeong": {
    "name": "대유평공원 반려동물 배변수거함",
    "address": "경기 수원시 장안구 정자동 111-19",
    "kind": "배변 수거함",
    "source": "https://news.suwon.go.kr/?mode=photo&p=40&page=73&reqIdx=202406191706299891&viewMode=view",
    "provider": "수원시 인터넷신문",
    "sourceDate": "2024-06-19",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "수원시 시민기자 취재에서 장안구청이 관리하는 공원 내 배변수거함 설치를 확인했습니다. 일반 생활쓰레기는 넣지 마세요.",
    "secondary": ""
  },
  "bin_seonggok": {
    "name": "성곡반려견놀이터 배변수거함",
    "address": "경기도 안산시 단원구 성곡동 696",
    "kind": "배변 수거함",
    "source": "https://www.ansan.go.kr/ansantalktalk/content/ansantalk/cityNews.html?fidx=8369&opt=&page=2042&pg=vv&sword=",
    "provider": "안산시",
    "sourceDate": null,
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "공식 개장 자료에서 배변봉투 공급함과 수거함을 확인했습니다. 시설 자료가 오래되어 방문 전 현재 운영·입장 조건과 수거함 이용 가능 여부를 확인하세요.",
    "secondary": ""
  },
  "bin_geoje-yongsan": {
    "name": "거제 용산쉼터 반려견놀이터 배변수거함",
    "address": "경상남도 거제시 상동동 161-3 일원",
    "kind": "배변 수거함",
    "source": "https://www.geoje.go.kr/board/view.geoje?boardId=BBS_0000028&dataSid=306080481&keyword=%EA%B3%A0%ED%98%84&menuCd=DOM_000008902003004000&paging=ok&searchType=DATA_TITLE&startPage=8",
    "provider": "거제시",
    "sourceDate": "2023-08-07",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "공식 개장 자료에서 놀이터 내 배변수거함 설치를 확인했습니다. 동물등록을 완료한 중·소형견 대상 시설로 안내되어 있으니 현재 입장 기준과 운영시간을 확인하세요.",
    "secondary": ""
  },
  "bin_ulsan": {
    "name": "울산 남구 애견운동공원 배변수거함",
    "address": "울산광역시 남구 남부순환도로 209",
    "kind": "배변 수거함",
    "source": "https://www.ulsannamgu.go.kr/cop/bbs/selectBoardArticle.do?bbsId=press&nttId=479462",
    "provider": "울산 남구",
    "sourceDate": "2025-06-04",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "문수국제양궁장 내 애견운동공원 시설 안내에서 배변봉투 수거함을 확인했습니다. 동물등록·입장료·운영시간 조건을 확인한 뒤 공원 이용 중 사용하세요.",
    "secondary": ""
  },
  "bin_gimcheon": {
    "name": "국립김천숲속야영장 반려견놀이터 배변수거함",
    "address": "경상북도 김천시 대덕면 조룡길 865",
    "kind": "배변 수거함",
    "source": "https://www.gocamping.or.kr/bsite/camp/info/read.do?c_no=101520&viewType=read02",
    "provider": "한국관광공사 고캠핑",
    "sourceDate": "2026-07-23",
    "checkedDate": "2026-10-08",
    "pointType": "시설 대표 위치",
    "positionNote": "시설 대표 위치이며 수거함 자체의 정확한 좌표는 공개 자료로 확인되지 않았습니다. 현장에서 안내판과 설치 위치·작동 상태를 확인하세요.",
    "usage": "공식 시설 정보에서 대형·소형 반려견놀이터와 배변수거함을 확인했습니다. 야영장 예약·입장 조건이 있으며 외부 산책객 이용 가능 여부는 관리소에 먼저 문의하세요.",
    "secondary": ""
  }
};
  const get = item => entries[String(item?.id||"")] || null;
  const label = item => get(item)?.kind || "수거 여부 미확인";
  const api = Object.freeze({get,label,entries:Object.freeze(entries)});
  if(typeof module==="object"&&module.exports)module.exports=api;
  else root.BinInfo=api;
})(typeof globalThis!=="undefined"?globalThis:this);
