// Offline app shell only: no database responses, location data, ads or map tiles.
const CACHE_NAME='balzaguk-shell-v11-glass-login';
const SHELL_FILES=["./", "./index.html", "./manifest.json", "./icon-192.png", "./icon-512.png", "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.css", "https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.9.4/leaflet.min.js", "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.css", "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/MarkerCluster.Default.css", "https://cdnjs.cloudflare.com/ajax/libs/leaflet.markercluster/1.5.3/leaflet.markercluster.js", "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2", "https://cdnjs.cloudflare.com/ajax/libs/PapaParse/5.4.1/papaparse.min.js", "/legal.css?v=20261006-premium", "/home-premium.css?v=20261008-shopping", "traffic.js?v=20261003", "course-photos.js?v=20261004-expansion", "course-info.js?v=20261004-mfds-sources", "bin-info.js?v=20261008-disposal-sites", "/place-saves.js?v=20261008", "shopping-config.js?v=20261008", "shopping.js?v=20261008", "account-deletion-client.js?v=20261009", "auth-presentation.js?v=20261009", "/account-ui.css?v=20261009-glass", "facility-info.js?v=20261003", "course-routes.js?v=20261004-expansion", "course-expansion-300.js?v=20261004-300", "course-addresses.js?v=20261004-expansion", "walk-tracker.js?v=20261005-offline", "admin-bot-panel.js?v=20261004", "/readability.css?v=20261008-place-flow"];
const allowed=new Set(SHELL_FILES.map(path=>new URL(path,self.location.href).href));
self.addEventListener('install',event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>Promise.allSettled(SHELL_FILES.map(path=>cache.add(path)))).then(()=>self.skipWaiting()));});
self.addEventListener('activate',event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(k=>k.startsWith('balzaguk-shell-')&&k!==CACHE_NAME).map(k=>caches.delete(k)))).then(()=>self.clients.claim()));});
self.addEventListener('fetch',event=>{
 if(event.request.method!=='GET')return;
 const url=new URL(event.request.url),navigation=url.origin===self.location.origin&&event.request.mode==='navigate';
 if(!navigation&&!allowed.has(url.href))return;
 event.respondWith(fetch(event.request).then(response=>{if(response.ok&&(allowed.has(url.href)||navigation)){const copy=response.clone();event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy)).catch(()=>{}));}return response;}).catch(async()=>{const cache=await caches.open(CACHE_NAME);const hit=await cache.match(event.request);if(hit)return hit;if(navigation)return (await cache.match('./index.html'))||Response.error();return Response.error();}));
});
