const assert=require('node:assert/strict'),fs=require('node:fs'),zlib=require('node:zlib'),vm=require('node:vm');
const comfort=require('../course-comfort.js'),info=require('../course-info.js');
const courses=JSON.parse(zlib.gunzipSync(fs.readFileSync('docs/pet-access-audit-20261010/public-courses.json.gz'))).map(c=>({...c,desc:c.description}));
const by=id=>courses.find(c=>c.id===id);
const unknown={...by('c365'),tags:['계단없음','벤치','평지']};
assert(!comfort.matches(unknown,{stairs:true}));assert(!comfort.matches(unknown,{gentle:true}));assert(!comfort.matches(unknown,{rest:true}));
assert(comfort.labels(unknown).every(x=>x.includes('미확인')));
assert(comfort.matches(by('c133'),{stairs:true,rest:true,gentle:true}));
assert(!comfort.matches(by('c133'),{short:true}));
assert(comfort.matches(by('c388'),comfort.preset()));
assert(!comfort.matches(by('c388'),{stairs:true}));
assert(!comfort.get({...by('c388'),description:by('c388').description+' edited'}));
assert(!comfort.get({...by('c388'),path:by('c388').path.slice(1)}));
assert(!comfort.get({...by('c388'),name:'fake'}));
for(const value of ['不明','2-4km','0km','-1km','1500m terrain'])assert(!comfort.matches({distance:value},{short:true}));
assert(comfort.matches({distance:'2000m'},{short:true}));assert(!comfort.matches({distance:'2001m'},{short:true}));
const html=fs.readFileSync('index.html','utf8');
const listFunction=html.slice(html.indexOf('  function getFilteredCourses(){'),html.indexOf('  function hasActiveListFilter(){'));
const aiFunction=html.slice(html.indexOf('  function aiRecommendCourses(){'),html.indexOf('  function mongDistanceKm(value){'));
const state={query:'',diff:'all',tags:new Set(),maxMinutes:0,collection:'',favOnly:false,comfort:{}};
const ai={time:null,region:null,env:null,comfort:{}};
const sandbox={CourseComfort:comfort,listFilterState:state,aiAnswers:ai,allCourses:()=>courses,isHidden:()=>false,needsPetCheck:()=>false,courseInRegion:()=>true,courseMinutes:c=>info.walkTime(c.desc,c.distance).minutes,courseWalkTime:c=>info.walkTime(c.desc,c.distance),mongDistanceKm:c=>comfort.distance({distance:c}),CourseAddresses:{matches:()=>true}};
vm.createContext(sandbox);vm.runInContext(listFunction+aiFunction,sandbox);
assert.equal(sandbox.getFilteredCourses().length,205);
state.comfort=comfort.preset();assert.deepEqual(Array.from(sandbox.getFilteredCourses(),c=>c.id),['c388']);
ai.comfort=comfort.preset();assert.deepEqual(Array.from(sandbox.aiRecommendCourses(),c=>c.id),['c388']);
state.comfort={};state.tags.add('계단없음');assert.deepEqual(Array.from(sandbox.getFilteredCourses(),c=>c.id),['c133']);
ai.comfort={};ai.env='계단없음';assert.deepEqual(Array.from(sandbox.aiRecommendCourses(),c=>c.id),['c133']);
ai.comfort={stairs:true,short:true};assert.equal(sandbox.aiRecommendCourses().length,0); // no relaxed fallback
state.tags.clear();state.comfort={stairs:true,short:true};assert.equal(sandbox.getFilteredCourses().length,0);
state.comfort={};assert.equal(sandbox.getFilteredCourses().length,205);
assert(html.includes("listFilterState.comfort={};"));assert(html.includes('CourseComfort.read(body.querySelector'));
assert(comfort.panel(unknown).includes('未確認')===false);assert(comfort.panel(unknown).includes('미확인'));
console.log('PASS: strict unknown exclusion, source/geometry binding, distance boundaries, senior preset, list/Mong parity, legacy stair filter and empty-result fallback.');
